### PR TITLE
TE-1221 Create Http ApplicationExtension

### PR DESCRIPTION
**Pull request by gechetspr**
- Developer(s): @stereomon

- Ticket: https://spryker.atlassian.net/browse/TE-1221

- Release Group: https://release.spryker.com/release-groups/view/1991

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Silexphp              | patch (currently 0.x)  |                       |

#### Release Notes

{skip}

-----------------------------------------

##### Change log

Initial Release

- Deprecated `Silex\Provider\HttpFragmentServiceProvider`.

### CODE REVIEW

**Comment by dereuromark** [comment]
Is this merge only?

**Comment by gechetspr** [comment]
Not sure. As I know, we release deprecation as a patch.

**Comment by dereuromark** [comment]
Only if it has real value, otherwise this will release itself with next release.

**Comment by gechetspr** [comment]
In this case it can be merge only. But we had a problem with twig integration for one customer, because there were no deprecation message for one of the service providers.

**Comment by stereomon** [comment]
Please release these deprecations as a patch.

**Comment by dereuromark** [comment]
The patch is not necessary if a follow up release is done, which seems the case.
We dont patch this here then.

**Comment by stereomon** [comment]
We need to release these deprecations when we release the core and project code which replaces this one. Projects need to see the deprecation to see that there is a replacement for this.

We are refactoring our code to get rid of silex. Every change in this module is only about deprecating something or fix tests. There will be no feature release.

IMO it doesn't matter if we make 10 or more patch releases here it's more vital to inform projects properly with deprecations.

On the other hand, when we only release one patch at the end of the refactoring projects might be overwhelmed from changes they have to make when they get 10 deprecations with one patch.

**Pull request merged**
